"""Dependency-light shared constants and stable vocabularies for SemaPact.

Existing imports from ``semapact.constants`` remain supported while definitions are
organized into focused submodules.
"""

from semapact.constants.editor import (
    BUSINESS_PROPERTY_KEYS,
    CHANGE_FILTER_OPTIONS,
    CONTRACT_STATUS_OPTIONS,
    DEFAULT_QUALITY_SEVERITY,
    DEFAULT_QUALITY_TYPE,
    EDITABLE_PROPERTY_FIELDS,
    EDITABLE_SCHEMA_FIELDS,
    LIFECYCLE_OPTIONS,
    QUALITY_SEVERITY_OPTIONS,
    QUALITY_TYPE_OPTIONS,
    READ_ONLY_CONTRACT_FIELDS,
    TABLE_RULE_COLUMN,
    TECHNICAL_PROPERTY_KEYS,
    TYPE_OPTIONS,
)
from semapact.constants.governance_reasons import (
    GOVERNANCE_REASON_REGISTRY,
    GovernanceReasonCode,
    GovernanceReasonDefinition,
    GovernanceSeverity,
    reason_severity,
)
from semapact.constants.prompts import (
    COLUMN_DESC_SYSTEM_PROMPT_TEMPLATE,
    COLUMN_DESC_USER_PROMPT_TEMPLATE,
    JOIN_SYSTEM_PROMPT_TEMPLATE,
    JOIN_USER_PROMPT_TEMPLATE,
    LABEL_SYSTEM_PROMPT_TEMPLATE,
    LABEL_USER_PROMPT_TEMPLATE,
    QUALITY_SUGGESTION_SYSTEM_PROMPT_TEMPLATE,
    QUALITY_SUGGESTION_USER_PROMPT_TEMPLATE,
    TABLE_DESC_SYSTEM_PROMPT_TEMPLATE,
    TABLE_DESC_USER_PROMPT_TEMPLATE,
)
from semapact.constants.unity import (
    UNITY_CONSTRAINT_NAME_KEY,
    UNITY_RELATIONSHIPS_COUNT_KEY,
    UNITY_RELATIONSHIPS_IMPORTED_KEY,
    UNITY_RELATIONSHIPS_REASON_KEY,
)

__all__ = [
    "TYPE_OPTIONS",
    "LIFECYCLE_OPTIONS",
    "CONTRACT_STATUS_OPTIONS",
    "QUALITY_TYPE_OPTIONS",
    "QUALITY_SEVERITY_OPTIONS",
    "CHANGE_FILTER_OPTIONS",
    "TABLE_RULE_COLUMN",
    "DEFAULT_QUALITY_TYPE",
    "DEFAULT_QUALITY_SEVERITY",
    "READ_ONLY_CONTRACT_FIELDS",
    "EDITABLE_SCHEMA_FIELDS",
    "EDITABLE_PROPERTY_FIELDS",
    "TECHNICAL_PROPERTY_KEYS",
    "BUSINESS_PROPERTY_KEYS",
    "UNITY_RELATIONSHIPS_IMPORTED_KEY",
    "UNITY_RELATIONSHIPS_COUNT_KEY",
    "UNITY_RELATIONSHIPS_REASON_KEY",
    "UNITY_CONSTRAINT_NAME_KEY",
    "LABEL_SYSTEM_PROMPT_TEMPLATE",
    "LABEL_USER_PROMPT_TEMPLATE",
    "JOIN_SYSTEM_PROMPT_TEMPLATE",
    "JOIN_USER_PROMPT_TEMPLATE",
    "TABLE_DESC_SYSTEM_PROMPT_TEMPLATE",
    "TABLE_DESC_USER_PROMPT_TEMPLATE",
    "COLUMN_DESC_SYSTEM_PROMPT_TEMPLATE",
    "COLUMN_DESC_USER_PROMPT_TEMPLATE",
    "QUALITY_SUGGESTION_SYSTEM_PROMPT_TEMPLATE",
    "QUALITY_SUGGESTION_USER_PROMPT_TEMPLATE",
    "GovernanceReasonCode",
    "GovernanceSeverity",
    "GovernanceReasonDefinition",
    "GOVERNANCE_REASON_REGISTRY",
    "reason_severity",
]
